### ISSUE TITLE
Travis Build is Failing

### ISSUE THREAD

**Issue by mjp59** [mjp59/bme590hrm#3]
https://github.com/mjp59/bme590hrm/blob/d36f6d6ba29477c282d8359392f53fe798fa6af3/.travis.yml#L1-L9

This is the content of my .travis.yml file.

**Comment by mlp6** [comment]
Can you share an example of the failing test output here?  URL to the Travis page, or cut-n-paste... URL would be preferred.

**Comment by mjp59** [comment]
https://travis-ci.com/mjp59/bme590hrm/builds/89053804?utm_medium=notification&utm_source=email

**Comment by dward2** [comment]
In your .travis.yml file, try changing the python version from "3" to "3.6".  When I put in only "3" in one of my .travis.yml files, I got a similar error.

**Comment by mjp59** [comment]
that worked. Thank you!
